"""
인포그래픽 자동 생성 서비스
콘텐츠에서 핵심 데이터를 추출하여 HTML 인포그래픽 생성
"""
import html
import logging
import re
from typing import Dict, List

logger = logging.getLogger(__name__)


def _extract_key_points(content: str) -> List[str]:
    """콘텐츠에서 핵심 포인트를 추출합니다."""
    points = []

    # 마크다운 헤딩 추출
    headings = re.findall(r'^#{1,3}\s+(.+)$', content, re.MULTILINE)
    for h in headings[:8]:
        cleaned = re.sub(r'[*_`]', '', h).strip()
        if cleaned and len(cleaned) > 2:
            points.append(cleaned)

    # 리스트 아이템 추출
    if len(points) < 4:
        items = re.findall(r'^[\-\*\+]\s+(.+)$', content, re.MULTILINE)
        for item in items:
            cleaned = re.sub(r'[*_`]', '', item).strip()
            if cleaned and len(cleaned) > 5 and cleaned not in points:
                points.append(cleaned)
                if len(points) >= 8:
                    break

    # 번호 리스트 추출
    if len(points) < 4:
        numbered = re.findall(r'^\d+\.\s+(.+)$', content, re.MULTILINE)
        for item in numbered:
            cleaned = re.sub(r'[*_`]', '', item).strip()
            if cleaned and len(cleaned) > 5 and cleaned not in points:
                points.append(cleaned)
                if len(points) >= 8:
                    break

    return points[:8]


def _extract_stats(content: str) -> List[Dict[str, str]]:
    """콘텐츠에서 숫자/통계 데이터를 추출합니다."""
    stats = []
    # 숫자 + 단위/퍼센트 패턴
    patterns = re.findall(
        r'([\d,]+(?:\.\d+)?)\s*(%, 개, 건, 원, 명, 회, 시간|배|만|억|조)?',
        content
    )
    for value, unit in patterns[:6]:
        if len(value) >= 2:  # 의미 있는 숫자만
            stats.append({'value': value, 'unit': unit or ''})
    return stats[:4]


def generate_infographic(content: str, title: str) -> str:
    """콘텐츠를 HTML 인포그래픽으로 변환합니다.

    Args:
        content: 원본 마크다운 콘텐츠
        title: 인포그래픽 제목

    Returns:
        인라인 CSS 포함 독립 HTML 문자열
    """
    if not content:
        return '<p>콘텐츠가 없습니다.</p>'

    safe_title = html.escape(title or '인포그래픽')
    key_points = _extract_key_points(content)
    stats = _extract_stats(content)

    # 색상 팔레트
    colors = ['#4F46E5', '#7C3AED', '#EC4899', '#F59E0B', '#10B981', '#06B6D4', '#F97316', '#6366F1']

    # 핵심 포인트 HTML
    points_html = ''
    for i, point in enumerate(key_points):
        color = colors[i % len(colors)]
        safe_point = html.escape(point)
        points_html += f'''
        <div style="display:flex;align-items:flex-start;gap:12px;margin-bottom:16px;">
            <div style="min-width:36px;height:36px;border-radius:50%;background:{color};
                        color:#fff;display:flex;align-items:center;justify-content:center;
                        font-weight:700;font-size:16px;">{i+1}</div>
            <p style="margin:0;padding-top:6px;font-size:15px;color:#374151;line-height:1.5;">{safe_point}</p>
        </div>'''

    # 통계 HTML
    stats_html = ''
    if stats:
        stats_items = ''
        for i, stat in enumerate(stats):
            color = colors[i % len(colors)]
            stats_items += f'''
            <div style="text-align:center;padding:16px;">
                <div style="font-size:28px;font-weight:800;color:{color};">{html.escape(stat["value"])}{html.escape(stat["unit"])}</div>
            </div>'''
        stats_html = f'''
        <div style="display:flex;justify-content:space-around;flex-wrap:wrap;
                    background:#F9FAFB;border-radius:12px;padding:16px;margin-bottom:24px;">
            {stats_items}
        </div>'''

    return f'''<!DOCTYPE html>
<html lang="ko">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#fff;">
<div style="max-width:680px;margin:0 auto;padding:32px 24px;">
    <h1 style="text-align:center;font-size:24px;font-weight:800;color:#111827;
               margin-bottom:8px;line-height:1.3;">{safe_title}</h1>
    <div style="width:60px;height:4px;background:linear-gradient(90deg,#4F46E5,#EC4899);
                margin:0 auto 28px;border-radius:2px;"></div>
    {stats_html}
    <div style="padding:0 8px;">
        {points_html}
    </div>
    <div style="text-align:center;margin-top:24px;padding-top:16px;border-top:1px solid #E5E7EB;">
        <span style="font-size:12px;color:#9CA3AF;">Generated by Insight Engine</span>
    </div>
</div>
</body>
</html>'''
