"""
요약 카드 이미지 생성 서비스
제목 + 핵심 포인트 → 공유용 SVG 카드
"""
import html
import logging
from typing import List

logger = logging.getLogger(__name__)


def _wrap_lines(text: str, max_chars: int = 24) -> List[str]:
    """텍스트를 최대 글자수로 줄바꿈합니다."""
    if len(text) <= max_chars:
        return [text]
    lines = []
    current = ''
    for char in text:
        current += char
        if len(current) >= max_chars:
            lines.append(current)
            current = ''
    if current:
        lines.append(current)
    return lines[:3]


def generate_summary_card(title: str, key_points: List[str]) -> str:
    """제목 + 핵심 3줄 → 공유용 SVG 카드를 생성합니다.

    Args:
        title: 콘텐츠 제목
        key_points: 핵심 포인트 리스트 (최대 5개)

    Returns:
        SVG 문자열
    """
    safe_title = html.escape(title or '요약')
    points = [html.escape(p) for p in (key_points or [])[:5]]

    title_lines = _wrap_lines(safe_title, 20)
    title_tspans = _build_title_tspans(title_lines)
    points_start_y = 160 + len(title_lines) * 36
    points_svg = _build_points_svg(points, points_start_y)
    card_height = max(400, points_start_y + len(points) * 52 + 80)

    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="800" height="{card_height}" viewBox="0 0 800 {card_height}">
  <rect width="800" height="{card_height}" rx="20" fill="#FFFFFF" stroke="#E5E7EB" stroke-width="1"/>
  <rect x="0" y="0" width="800" height="8" rx="4" fill="url(#accent)"/>
  <defs>
    <linearGradient id="accent" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#4F46E5"/>
      <stop offset="100%" style="stop-color:#EC4899"/>
    </linearGradient>
  </defs>
  <text x="400" y="80" text-anchor="middle" fill="#111827" font-size="28" font-weight="800"
        font-family="-apple-system,BlinkMacSystemFont,sans-serif">{title_tspans}</text>
  <line x1="60" y1="{points_start_y - 30}" x2="740" y2="{points_start_y - 30}"
        stroke="#E5E7EB" stroke-width="1"/>
  {points_svg}
  <text x="400" y="{card_height - 20}" text-anchor="middle" fill="#9CA3AF" font-size="12"
        font-family="-apple-system,sans-serif">Generated by Insight Engine</text>
</svg>'''


def _build_title_tspans(title_lines: List[str]) -> str:
    """제목 줄바꿈을 SVG tspan 요소로 변환합니다."""
    parts = []
    for i, line in enumerate(title_lines):
        dy = '0' if i == 0 else '36'
        parts.append(f'<tspan x="400" dy="{dy}">{line}</tspan>')
    return ''.join(parts)


def _build_points_svg(points: List[str], start_y: int) -> str:
    """핵심 포인트를 SVG 요소로 변환합니다."""
    parts = []
    for i, point in enumerate(points):
        y = start_y + i * 52
        display_text = point if len(point) <= 30 else point[:28] + '…'
        parts.append(f'''
    <circle cx="90" cy="{y}" r="6" fill="#4F46E5"/>
    <text x="110" y="{y + 5}" fill="#374151" font-size="18"
          font-family="-apple-system,BlinkMacSystemFont,sans-serif">{display_text}</text>''')
    return ''.join(parts)
